# Based on https://github.com/craigcitro/r-travis/blob/master/sample.travis.yml

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

r_github_packages:
  - jimhester/covr

install:
  cd cheddar
  - ../travis-tool.sh install_deps

script: ../travis-tool.sh run_tests

after_success:
  - Rscript -e 'library(covr);coveralls("cheddar")'

after_failure:
  - ../travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
