sudo: false
language: r
r: devel

warnings_are_errors: false

before_install:
  - tlmgr install hyphenat

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
